name: Run

on:
  push:
    branches:
      - main
      - test
      - hch
  pull_request:
    branches:
      - main
      - test

env:
  HOST: 154.37.220.49  # 部署的服务器地址
  USER: root # 部署的服务器用户名
  GOPROXY: https://goproxy.cn,direct
  PRIVATE_KEY: ${{ secrets.SSH_KEY }} # 部署的服务器私钥
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKERHUB_USER }} # Docker Hub 用户名
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }} # Docker Hub 访问令牌

jobs:
