name: Run

on:
  push:
    branches:
      - main
      - test
      - hch
  pull_request:
    branches:
      - main
      - test

#env:
#  HOST: 139.159.145.82  # 部署的服务器地址
#  USER: root # 部署的服务器用户名
#  GOPROXY: https://goproxy.cn,direct
#  PRIVATE_KEY: ${{ secrets.SSH_KEY }} # 部署的服务器私钥

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整的历史记录

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub (optional)
        if: github.event_name == 'push'  # 仅在 push 时登录 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.yml build

      - name: Start Docker containers
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Run tests (optional)
        run: |
          docker-compose exec frontend go test ./...
          docker-compose exec product go test ./...

      - name: Push Docker images (optional)
        if: github.event_name == 'push'  # 仅在 push 时推送镜像
        run: |
          docker-compose -f docker-compose.yml push
