name: Run

on:
  push:
    branches:
      - main
      - test
      - hch
  pull_request:
    branches:
      - main
      - test

#env:
#  HOST: 139.159.145.82  # 部署的服务器地址
#  USER: root # 部署的服务器用户名
#  GOPROXY: https://goproxy.cn,direct
#  PRIVATE_KEY: ${{ secrets.SSH_KEY }} # 部署的服务器私钥

jobs:
  run:
    runs-on: ubuntu-latestnohup

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整的历史记录

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Start docker
        run: make docker

      - name: Start user_run
        run: nohup make user_run # 后台运行

      - name: Start product_run
        run: nohup make product_run

      - name: Start cart_run
        run: nohup make cart_run

      - name: Start order_run
        run: nohup make order_run

      - name: Start payment_run
        run: nohup make payment_run

      - name: Start checkout_run
        run: nohup make checkout_run

      - name: Start email_run
        run: nohup make email_run

      - name: Start frontend_run
        run: nohup make frontend_run